In [2]:
import numpy as np

In [2]:
# 1 D array
array_1d = np.array([1, 2, 3, 4, 5])
print(f'1D Array:\n{array_1d}\n')

1D Array:
[1 2 3 4 5]



In [6]:
# 2 D array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f'2D Array:\n{array_2d}\n')

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [5]:
egg_carton1 = np.array([
  [0.89, 0.90, 0.83, 0.89, 0.97, 0.98], 
  [0.95, 0.95, 0.89, 0.95, 0.23, 0.99]
])

egg_carton2 = np.array([
  [0.89, 0.95, 0.84, 0.92, 0.94, 0.93], 
  [0.93, 0.95, 0.02, 0.03, 0.23, 0.99]
])

egg_carton3 = np.array([
  [0.83, 0.95, 0.89, 0.54, 0.37, 0.92], 
  [0.98, 0.99, 0.19, 0.23, 0.89, 0.91]
])

# # Rata rata skor kesegaran telur di setiap karton sebelum diubah
# average_freshness_carton1_before = np.mean(egg_carton1)
# average_freshness_carton2_before = np.mean(egg_carton2)
# average_freshness_carton3_before = np.mean(egg_carton3)
# print(f'Average freshness score in carton 1 before update: {average_freshness_carton1_before}')
# print(f'Average freshness score in carton 2 before update: {average_freshness_carton2_before}')
# print(f'Average freshness score in carton 3 before update: {average_freshness_carton3_before}')
# # The lowest freshness score for egg in cartoon 1, 2 and 3
# lowest_freshness_carton1 = np.min(egg_carton1)
# lowest_freshness_carton2 = np.min(egg_carton2)
# lowest_freshness_carton3 = np.min(egg_carton3)
# print(f'Lowest freshness score in carton 1: {lowest_freshness_carton1}')
# print(f'Lowest freshness score in carton 2: {lowest_freshness_carton2}')
# print(f'Lowest freshness score in carton 3: {lowest_freshness_carton3}')
# # Dapatkan posisi index dari telur dengan skor kesegaran terendah
# index_lowest_cartoon1 = np.unravel_index(egg_carton1.argmin(), egg_carton1.shape)
# index_lowest_cartoon2 = np.unravel_index(egg_carton2.argmin(), egg_carton2.shape)
# index_lowest_cartoon3 = np.unravel_index(egg_carton3.argmin(), egg_carton3.shape)
# print(f'Index of lowest freshness score in carton 1: {index_lowest_cartoon1}')
# print(f'Index of lowest freshness score in carton 2: {index_lowest_cartoon2}')
# print(f'Index of lowest freshness score in carton 3: {index_lowest_cartoon3}')
# # Mengubah nilai skor kesegaran terendah menjadi 1.0
# egg_carton2[index_lowest_cartoon2] = 1.0
# print(f'Updated egg cartoon 2:\n{egg_carton2}')
# # Mengubah nilai degan masking
# egg_carton1[egg_carton1 <= 0.23] = 1.0
# print(f'Updated egg cartoon 1:\n{egg_carton1}')
# egg_carton3[egg_carton3 < 0.5] = 1.0
# print(f'Updated egg cartoon 3:\n{egg_carton3}')
# # Rata-rata skor kesegaran telur di setiap karton
# average_freshness_carton1 = np.mean(egg_carton1)
# average_freshness_carton2 = np.mean(egg_carton2)
# average_freshness_carton3 = np.mean(egg_carton3)
# print(f'Average freshness score in carton 1: {average_freshness_carton1}')
# print(f'Average freshness score in carton 2: {average_freshness_carton2}')
# print(f'Average freshness score in carton 3: {average_freshness_carton3}')
# # Bandingkan 2 karton telur, lalu cari posisi telur yang lebih segar di karton 1 dibandingkan karton 2
# fresher_eggs_carton1 = egg_carton1 > egg_carton2
# print(f'Positions of eggs fresher in carton 1 than carton 2:\n{fresher_eggs_carton1}')
# # Menghitung jumlah true values pada array fresher_eggs_carton1
# num_fresher_eggs_carton1 = np.sum(fresher_eggs_carton1)
# print(f'Number of eggs fresher in carton 1 than carton 2: {num_fresher_eggs_carton1}')
# Menggabungkan 2 karton telur secara vertikal
combined_carton_vertical = np.vstack((egg_carton1, egg_carton2))
print(f'Combined egg carton vertically:\n{combined_carton_vertical}')
# Menggabungkan 2 karton telur secara horizontal
combined_carton_horizontal = np.hstack((egg_carton1, egg_carton2))
print(f'Combined egg carton horizontally:\n{combined_carton_horizontal}')
# .shape untuk mengetahui dimensi array
print(f'Dimensions of combined carton vertically: {combined_carton_vertical.shape}')
print(f'Dimensions of combined carton horizontally: {combined_carton_horizontal.shape}')
# total seluruh elemen dalam array gabungan
print(f'Total elements in combined carton vertically: {combined_carton_vertical.size}')
print(f'Total elements in combined carton horizontally: {combined_carton_horizontal.size}')
# mengubah bentuk array gabungan menjadi 4 baris dan 6 kolom
reshaped_combined_carton = combined_carton_horizontal.reshape(4, 6)
print(f'Reshaped combined carton (4x6):\n{reshaped_combined_carton}')
# print(combined_carton_horizontal.reshape(4, 6)) # cara singkat
# coba dengan cara singkat + otomatis
print(combined_carton_horizontal.reshape(3, -1))  # 3 baris, kolom otomatis
reshaped_combined_horizontal = combined_carton_horizontal.reshape(4, 6)
# ambil sampel pada 2 baris pertama dan 3 kolom pertama
# sample_2x3 = reshaped_combined_horizontal[:2, :3]
# print(f'Sample 2 rows and 3 columns from reshaped combined carton:\n{sample_2x3}')
# ambil telur pada index 3 valuenya genap aja
even_eggs_index = reshaped_combined_horizontal[3, ::2]
print(f'Values at index 3 with even columns:\n{even_eggs_index}')
egg_prices = reshaped_combined_horizontal * 2000
print(f'Egg prices based on freshness scores:\n{egg_prices}')
total_revenue = np.sum(egg_prices)
print(f'Total sales from all eggs: {total_revenue}')
# Cek dimensi array egg_prices pakai .ndim
print(f'Dimensions of egg prices array: {egg_prices.ndim}')

Combined egg carton vertically:
[[0.89 0.9  0.83 0.89 0.97 0.98]
 [0.95 0.95 0.89 0.95 0.23 0.99]
 [0.89 0.95 0.84 0.92 0.94 0.93]
 [0.93 0.95 0.02 0.03 0.23 0.99]]
Combined egg carton horizontally:
[[0.89 0.9  0.83 0.89 0.97 0.98 0.89 0.95 0.84 0.92 0.94 0.93]
 [0.95 0.95 0.89 0.95 0.23 0.99 0.93 0.95 0.02 0.03 0.23 0.99]]
Dimensions of combined carton vertically: (4, 6)
Dimensions of combined carton horizontally: (2, 12)
Total elements in combined carton vertically: 24
Total elements in combined carton horizontally: 24
Reshaped combined carton (4x6):
[[0.89 0.9  0.83 0.89 0.97 0.98]
 [0.89 0.95 0.84 0.92 0.94 0.93]
 [0.95 0.95 0.89 0.95 0.23 0.99]
 [0.93 0.95 0.02 0.03 0.23 0.99]]
[[0.89 0.9  0.83 0.89 0.97 0.98 0.89 0.95]
 [0.84 0.92 0.94 0.93 0.95 0.95 0.89 0.95]
 [0.23 0.99 0.93 0.95 0.02 0.03 0.23 0.99]]
Values at index 3 with even columns:
[0.93 0.02 0.23]
Egg prices based on freshness scores:
[[1780. 1800. 1660. 1780. 1940. 1960.]
 [1780. 1900. 1680. 1840. 1880. 1860.]
 [1900. 